apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-pv-volume
  labels:
    type: local
spec:
  storageClassName: mapr-edf
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/mapr_nfs/df5node/data/airflow/dags"