apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/hpadmin/pachyderm"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/hpadmin/pachyderm"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-3
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/hpadmin/pachyderm"
