CREATE TABLE IF NOT EXISTS fhvhv (
hvfhs_license_num varchar(255) ,
dispatching_base_num varchar(255) ,
originating_base_num varchar(255) ,
request_datetime timestamp ,
on_scene_datetime timestamp ,
pickup_datetime timestamp ,
dropoff_datetime timestamp ,
PULocationID bigint ,
DOLocationID bigint ,
trip_miles double precision ,
trip_time bigint ,
base_passenger_fare double precision ,
tolls double precision ,
bcf double precision ,
sales_tax double precision ,
congestion_surcharge double precision ,
airport_fee double precision ,
tips double precision ,
driver_pay double precision ,
shared_request_flag varchar(255) ,
shared_match_flag varchar(255) ,
access_a_ride_flag varchar(255) ,
wav_request_flag varchar(255) ,
wav_match_flag varchar(255) );